# 1. K?t n?i SQL Server (S? d?ng Database CalendarDB b?n ?ã t?o)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AppDB;encrypt=true;trustServerCertificate=true

# 2. Tài kho?n và m?t kh?u (Kh?p v?i tài kho?n sa b?n v?a reset)
spring.datasource.username=sa
spring.datasource.password=123456

# 3. C?u hình Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. Hibernate & JPA (??ng b? hóa Class Java và Table SQL)
# 'update' s? t? ??ng t?o b?ng n?u thi?u ho?c c?p nh?t n?u b?n ??i code
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? các câu l?nh SQL mà Java th?c thi xu?ng Console ?? b?n d? debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Quy ??nh ki?u ph??ng ng? cho SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect